In [1]:
import numpy as np
from scipy.linalg import lu

### Solve the following system of equations using LU Decomposition method:
#### Find L and U by hand.
#### Confirm that A=LU then solve.
- Ex1. 𝟐𝒙+𝟓𝒚=𝟐𝟏, 𝒙+𝟐𝒚=𝟖.
- Ex2. 𝒙𝟏+𝒙𝟐+𝒙𝟑=𝟏, 𝟒𝒙𝟏+𝟑𝒙𝟐−𝒙𝟑=𝟔, 𝟑𝒙𝟏+𝟓𝒙_𝟐+𝟑𝒙𝟑=𝟒

#### Use scipy.linalg.lu() to slove the previous system using LU decomposition and compare the results.

### Note (when using scipy):
- In the second system of equations We can see the <b>L and U</b> we get are different from the ones we got by hand. 
- You will also see there is a permutation matrix <b>P</b> that returned by the <b>lu function</b>. 
- This permutation matrix record how do we change the order of the equations for easier calculation purposes (for example, if first element in first row is zero, it can not be the pivot equation, since you can not turn the first elements in other rows to zero. Therefore, we need to switch the order of the equations to get a new pivot equation). 
- If you multiply <b>P with A</b>, you will see that this permutation matrix effect.
- You will need to arrange the ouput based on the new matrix <b>A</b> achieved by <b>LU</b> multiplication in order to correctly solve the system of equations.

In [2]:
A =np.array([[2,5],
 [1,2]])
y=np.array([[21],
 [ 8]])
p, l, u = lu(A)

In [3]:
l_inv=np.linalg.inv(l)
M=l_inv @ y
M

array([[21. ],
       [-2.5]])

In [4]:
u_inv=np.linalg.inv(u)
X=u_inv @ M
X

array([[-2.],
       [ 5.]])

In [5]:
LU=l@u

M=u@X
print(LU)
print("-----------")
print(M)

[[2. 5.]
 [1. 2.]]
-----------
[[21. ]
 [-2.5]]


In [6]:
print(p)
print("-----------")
print(l)
print("-------------")
print(u)

[[1. 0.]
 [0. 1.]]
-----------
[[1.  0. ]
 [0.5 1. ]]
-------------
[[ 2.   5. ]
 [ 0.  -0.5]]


---------------------------------------------------------------------------------------------------------------------

In [7]:
A =np.array([[ 1 , 1 , 1],
 [ 4 , 3 ,-1],
 [ 3 , 5 , 3]])
y=np.array([[1],
 [ 6],[4]])
p, l, u = lu(A)

In [8]:
p_inv=np.linalg.inv(p)
y_new= p_inv @ y
y_new

array([[6.],
       [4.],
       [1.]])

In [9]:
LU=l@u
LU

array([[ 4.,  3., -1.],
       [ 3.,  5.,  3.],
       [ 1.,  1.,  1.]])

In [10]:
l_inv=np.linalg.inv(l)
M=l_inv @ y_new
M

array([[ 6.        ],
       [-0.5       ],
       [-0.45454545]])

In [11]:
u_inv=np.linalg.inv(u)
X=u_inv @ M
X

array([[ 1. ],
       [ 0.5],
       [-0.5]])

In [12]:
print(p)
print("------------")
print(l)
print("-------------")
print(u)
print("------------")
print(LU)
print("-----------")
print(A)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
------------
[[1.         0.         0.        ]
 [0.75       1.         0.        ]
 [0.25       0.09090909 1.        ]]
-------------
[[ 4.          3.         -1.        ]
 [ 0.          2.75        3.75      ]
 [ 0.          0.          0.90909091]]
------------
[[ 4.  3. -1.]
 [ 3.  5.  3.]
 [ 1.  1.  1.]]
-----------
[[ 1  1  1]
 [ 4  3 -1]
 [ 3  5  3]]


In [13]:
print(M)
print("------------")
print(X)

[[ 6.        ]
 [-0.5       ]
 [-0.45454545]]
------------
[[ 1. ]
 [ 0.5]
 [-0.5]]


### Apply the Jacobi and Gauss-Seidel method to solve
- 𝟓𝒙𝟏−𝟐𝒙𝟐+𝟑𝒙𝟑=−𝟏, −𝟑𝒙𝟏+𝟗𝒙𝟐+𝒙𝟑=𝟐, 𝟐𝒙𝟏−𝒙𝟐−𝟕𝒙𝟑=𝟑
- Solve once without vectorization then use vectorize implementation.
- Check for convergance.
- Use different tolerence and see the difference between the two methods. e.g. tol: 0.01,0.001,0.0001 ... etc.

# Without_vectorization

In [14]:
A = np.array([[5, -2, 3],
     [-3, 9, 1],
     [2, -1, -7]])
def check_convergence(A):
    diag=abs(np.diag(A))
    off_diag=abs(abs(A)-np.diag(diag))
    off_diagonal=np.sum(off_diag,axis=1)
    if (diag > off_diagonal).all():
        print("stricly  dominant")
    elif (diag ==off_diagonal).any():
        print("diagonally dominant")
    else :
        print("not dominant")

In [15]:
A = np.array([[5, -2, 3],
     [-3, 9, 1],
     [2, -1, -7]])

check_convergence(A)

diagonally dominant


# Jacobi(not_vect)

In [16]:
x1=0
x2=0
x3=0
e=[]
x1_temp=[]
x2_temp=[]
x3_temp=[]
for i in range(100):
    x1_temp.append((2/5)*x2-(3/5)*x3-(1/5))
    x2_temp.append((1/3)*x1-(1/9)*x3+(2/9))
    x3_temp.append((2/7)*x1-(1/7)*x2-(3/7))
    print("{} ,{}  ,{} \n".format(x1_temp[i],x2_temp[i],x3_temp[i]))
    
    x1=x1_temp[i]
    x2=x2_temp[i]
    x3=x3_temp[i]
    if(i>=1):
        e1=abs(x1_temp[i]-x1_temp[i-1])
        e2=abs(x2_temp[i]-x2_temp[i-1])
        e3=abs(x3_temp[i]-x3_temp[i-1])
        e=np.array([[e1],[e2],[e3]])
        if np.linalg.norm(e)<0.00001:
                print("break at {}".format(i))
                break
       
    
    
    

-0.2 ,0.2222222222222222  ,-0.42857142857142855 

0.146031746031746 ,0.20317460317460317  ,-0.5174603174603174 

0.19174603174603166 ,0.32839506172839505  ,-0.41587301587301584 

0.18088183421516751 ,0.33234567901234563  ,-0.42070042831947596 

0.18535852859662383 ,0.3292606589961087  ,-0.4243688586545729 

0.18632557879118722 ,0.3311604938271605  ,-0.42264908597183726 

0.18605364911396655 ,0.3312917580383776  ,-0.42264419089211225 

0.1861032177506184 ,0.3312005709148902  ,-0.42274063711577775 

0.18612461063542268 ,0.3312278100408481  ,-0.42271344791623616 

0.18611919276608097 ,0.33123191998027823  ,-0.42271122696714325 

break at 9


In [17]:
## Jacobi Not Vectorized
epsilon = 0.00001

# Gauss

In [18]:
x1=0
x2=0
x3=0
e=[]
x1_temp=[]
x2_temp=[]
x3_temp=[]
for i in range(100):
    x1=((2/5)*x2-(3/5)*x3-(1/5))
    x1_temp.append(x1)
    x2=((1/3)*x1-(1/9)*x3+(2/9))
    x2_temp.append(x2)
    x3=((2/7)*x1-(1/7)*x2-(3/7))
    x3_temp.append(x3)
    print("{} ,{}  ,{} \n".format(x1_temp[i],x2_temp[i],x3_temp[i]))
    
    
    if(i>=1):
        e1=abs(x1_temp[i]-x1_temp[i-1])
        e2=abs(x2_temp[i]-x2_temp[i-1])
        e3=abs(x3_temp[i]-x3_temp[i-1])
        e=np.array([[e1],[e2],[e3]])
        if np.linalg.norm(e)<0.00001:
                print("break at {}".format(i))
                break
       
    

-0.2 ,0.15555555555555556  ,-0.5079365079365079 

0.16698412698412696 ,0.33432098765432094  ,-0.42862181909800956 

0.19090148652053412 ,0.33348069762884575  ,-0.4216682463696825 

0.18639322687334775 ,0.3312053252210806  ,-0.42263126735348355 

0.18606089050052232 ,0.3312015487616723  ,-0.42272568110866104 

0.18611602816986555 ,0.3312304184020286  ,-0.4227140517231853 

0.18612059839472267 ,0.3312306496563726  ,-0.4227127789809896 

break at 6


In [19]:
## Gauss-Seidel Not Vectorized
epsilon = 0.00001

In [20]:

A = np.array([[5, -2, 3],
     [-3, 9, 1],
     [2, -1, -7]])

b=np.array([[-1],[2],[3]])

In [21]:
x=np.array([[0],[0],[0]])
D=np.diag(np.diag(A))
u=np.triu(A, k=1)
print(u)
  #  l=np.tril(A, k=-1)

[[ 0 -2  3]
 [ 0  0  1]
 [ 0  0  0]]


In [22]:
def jacobi_vectorized(A,b):
    x=np.array([[0],[0],[0]])
    D=np.diag(np.diag(A))
    u=-1*np.triu(A, k=1)
    l=-1*np.tril(A, k=-1)
    D_inv=np.linalg.inv(D)
    T=D_inv @(l+u)
    spect,_=np.linalg.eig(T)
    c=D_inv @b
    X_list=[]
    X_list.append(x)
    for i in range(1000):
        x=T@x+c
        X_list.append(x)
        if np.linalg.norm(abs(X_list[i]-X_list[i-1]))< 0.00001and i>0:
            print("stop at {} iter".format(i))
            break 
    print("spectral_radius is {}".format(max(spect)))
    print(X_list[-1])



In [23]:
jacobi_vectorized(A,b)

stop at 10 iter
spectral_radius is (0.22199197113336008+0j)
[[ 0.1861195 ]
 [ 0.33122987]
 [-0.42271336]]


In [24]:
def gauss_vectorized(A,b):
    x=np.array([[0],[0],[0]])
    D=np.diag(np.diag(A))
    u=-1*np.triu(A, k=1)
    l=-1*np.tril(A, k=-1)
    Tg=np.linalg.inv(D-l) @ u
    cg=np.linalg.inv(D-l) @ b
    spect,_=np.linalg.eig(Tg)

    X_list=[]
    X_list.append(x)
    for i in range(1000):
        x=Tg@x+cg
        X_list.append(x)
        if np.linalg.norm(abs(X_list[i]-X_list[i-1]))< 0.00001and i>0:
            print("stop at {} iter".format(i))
            break 
    print("spectral_radius is {}".format(max(spect)))
    print(X_list[-1])


In [25]:
gauss_vectorized(A,b)

stop at 7 iter
spectral_radius is (0.003174603174603185+0.11264250793149314j)
[[ 0.18611993]
 [ 0.33123028]
 [-0.42271292]]


In [26]:
## Gauss-Seidel Vectorized
epsilon = 0.00001


### Use np.linalg.solve() to solve the previous system and compare the results.

In [27]:
np.linalg.solve(A,b)

array([[ 0.18611987],
       [ 0.33123028],
       [-0.42271293]])

### Use scipy.linalg.lu() to slove the previous system using LU decomposition and compare the results.

In [28]:
p,l,u=lu(A)

In [29]:
p

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
l

array([[ 1.        ,  0.        ,  0.        ],
       [-0.6       ,  1.        ,  0.        ],
       [ 0.4       , -0.02564103,  1.        ]])

In [32]:
u

array([[ 5.        , -2.        ,  3.        ],
       [ 0.        ,  7.8       ,  2.8       ],
       [ 0.        ,  0.        , -8.12820513]])

In [34]:
p_inv=np.linalg.inv(p)
y_new= p_inv @ b
y_new

array([[-1.],
       [ 2.],
       [ 3.]])

In [35]:
l_inv=np.linalg.inv(l)
M=l_inv @ b
M

array([[-1.        ],
       [ 1.4       ],
       [ 3.43589744]])

In [36]:
u_inv=np.linalg.inv(u)
X=u_inv @ M
X

array([[ 0.18611987],
       [ 0.33123028],
       [-0.42271293]])

A = [[ 5 -2  3]
 [-3  9  1]
 [ 2 -1 -7]]
LU =  [[ 5. -2.  3.]
 [-3.  9.  1.]
 [ 2. -1. -7.]]
M = [[-1.        ]
 [ 1.4       ]
 [ 3.43589744]]

Solution: 
x = [[ 0.1861206 ]
 [ 0.33123065]
 [-0.42271278]]
